#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# 저장소 루트에서 실행되도록 고정한다.
cd "$(dirname "$0")/.."

TOTAL_STAGES=7

# ask_db_url KEY "Prompt": Neon 연결 문자열을 숨김 입력으로 받고 형식을 확인한다.
ask_db_url() {
  local key="$1" prompt="$2"
  while true; do
    ask_secret "$key" "$prompt"
    if [[ "${!key}" =~ ^postgres(ql)?:// ]]; then return; fi
    warn "postgresql:// 로 시작하는 연결 문자열이 아닙니다. 다시 붙여넣어 주세요."
  done
}

# gen_secret: URL/환경변수에 안전한 무작위 문자열.
gen_secret() { openssl rand -base64 96 | tr -d '/+=\n' | cut -c1-"$1"; }

banner "투표 앱 환경 설정 (Neon + Vercel)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Neon 프로젝트 준비"
say "투표 앱이 쓸 Neon 프로젝트를 확인합니다."
open_url "https://console.neon.tech/app/projects"
step "이미 이 앱용 프로젝트가 있으면 그 프로젝트를 엽니다."
step "없으면 'New project'로 만듭니다. 리전은 Vercel과 가까운 곳(예: AWS Asia Pacific)을 고릅니다."
note "기본 브랜치 'main'이 운영 DB가 됩니다."
pause "프로젝트가 열려 있으면 Enter"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Neon 브랜치 dev, test 만들기"
say "개발용과 테스트용 브랜치를 main에서 갈라 만듭니다."
step "왼쪽 메뉴 'Branches' → 'New branch'(또는 'Create branch')를 누릅니다."
step "이름 dev, 부모(parent) main으로 만듭니다."
step "같은 방법으로 이름 test인 브랜치를 하나 더 만듭니다."
note "화면의 버튼 이름은 Neon 버전에 따라 조금 다를 수 있습니다."
pause "main, dev, test 세 브랜치가 보이면 Enter"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "dev 브랜치 연결 문자열 → .env.local"
ENV_FILE=".env.local"
step "프로젝트 대시보드에서 'Connect' 버튼을 누릅니다."
step "Branch를 dev로 바꾸고, 표시된 연결 문자열(postgresql://...)을 복사합니다."
if [[ -n "$(_existing DATABASE_URL || true)" ]]; then
  warn ".env.local에 DATABASE_URL이 이미 있습니다. dev 브랜치 값인지 모르면 새로 붙여넣으세요."
fi
ask_db_url DATABASE_URL "dev 연결 문자열 붙여넣기:"
DEV_DATABASE_URL="$DATABASE_URL"
write_env DATABASE_URL "$DEV_DATABASE_URL"
pause "Enter로 계속"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "test 브랜치 연결 문자열 → .env.test.local"
ENV_FILE=".env.test.local"
step "같은 'Connect' 창에서 Branch를 test로 바꾸고 연결 문자열을 복사합니다."
warn "테스트는 이 DB의 테이블을 매번 비웁니다. 반드시 test 브랜치 값을 넣으세요."
ask_db_url DATABASE_URL "test 연결 문자열 붙여넣기:"
TEST_DATABASE_URL="$DATABASE_URL"
if [[ "$TEST_DATABASE_URL" == "$DEV_DATABASE_URL" ]]; then
  warn "dev와 같은 값입니다. test 브랜치를 골랐는지 확인하세요."
  ask_db_url DATABASE_URL "test 연결 문자열 다시 붙여넣기:"
  TEST_DATABASE_URL="$DATABASE_URL"
fi
write_env DATABASE_URL "$TEST_DATABASE_URL"
pause "Enter로 계속"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "로컬용 운영자 비밀번호와 세션 키"
ENV_FILE=".env.local"
LOCAL_ADMIN_PASSWORD=$(_existing ADMIN_PASSWORD || true)
LOCAL_SESSION_SECRET=$(_existing SESSION_SECRET || true)
if [[ -n "$LOCAL_ADMIN_PASSWORD" && -n "$LOCAL_SESSION_SECRET" ]]; then
  note "이미 만들어 둔 값이 있어 그대로 둡니다."
else
  LOCAL_ADMIN_PASSWORD=$(gen_secret 24)
  LOCAL_SESSION_SECRET=$(gen_secret 64)
  write_env ADMIN_PASSWORD "$LOCAL_ADMIN_PASSWORD"
  write_env SESSION_SECRET "$LOCAL_SESSION_SECRET"
fi
say "로컬에서 /admin 에 로그인할 때 쓰는 비밀번호는 .env.local 의 ADMIN_PASSWORD 입니다."
pause "Enter로 계속"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Vercel에 GitHub 저장소 가져오기"
open_url "https://vercel.com/new"
step "'Import Git Repository'에서 Blongdin/voting-app 을 찾아 'Import'를 누릅니다."
note "목록에 없으면 'Adjust GitHub App Permissions'로 이 저장소 접근을 허용하세요."
step "Framework Preset이 Next.js 인지 확인합니다. 환경변수는 여기서 넣지 않습니다(다음 단계)."
step "'Deploy'를 누릅니다. 지금은 기본 시작 페이지가 배포됩니다."
pause "배포가 끝나고 프로젝트 화면이 보이면 Enter"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Vercel 환경변수 입력"
PROD_ADMIN_PASSWORD=$(gen_secret 24)
PROD_SESSION_SECRET=$(gen_secret 64)
step "프로젝트 → Settings → Environment Variables 로 갑니다."
say ""
say "${BOLD}1) DATABASE_URL${RESET} (환경마다 다른 값)"
step "Production 만 체크 → Neon 'Connect'에서 ${BOLD}main${RESET} 브랜치 연결 문자열을 복사해 넣고 Save"
step "Preview 만 체크 → ${BOLD}dev${RESET} 브랜치 연결 문자열을 넣고 Save"
say ""
say "${BOLD}2) ADMIN_PASSWORD${RESET} (Production, Preview) — 운영용, 로컬과 다름"
printf '     %s%s%s\n' "$YELLOW" "$PROD_ADMIN_PASSWORD" "$RESET"
say "${BOLD}3) SESSION_SECRET${RESET} (Production, Preview)"
printf '     %s%s%s\n' "$YELLOW" "$PROD_SESSION_SECRET" "$RESET"
say ""
warn "이 두 값은 파일에 저장되지 않고 지금 한 번만 보입니다."
warn "운영 ADMIN_PASSWORD 는 비밀번호 관리자에 꼭 보관하세요(운영 /admin 로그인용)."
note "잃어버리면 이 스크립트를 다시 돌려 새 값을 만들고 Vercel 값을 바꾸면 됩니다."
until confirm "세 변수를 모두 저장했고, 운영 비밀번호도 보관했나요?"; do
  say "저장을 마친 뒤 y 를 입력하세요."
done
_clear  # 화면에서 운영 비밀값을 지운다.

finish
say "다음 할 일: Claude에게 '/implement 01' 을 요청하세요."
say "운영(main) DB 스키마 적용과 푸시는 01 구현 끝에 확인 후 진행합니다."
printf '\n'
